"""
Slack Notification Service

Provides:
- Slack webhook integration for critical denial notifications
- Configurable notification settings
- Message formatting for security alerts
"""

import os
import logging
from typing import Optional, Dict, Any
from datetime import datetime

from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

logger = logging.getLogger(__name__)


class SlackService:
    """Service for sending Slack notifications."""

    def __init__(self):
        self.webhook_url = os.environ.get("SLACK_WEBHOOK_URL")
        self.bot_token = os.environ.get("SLACK_BOT_TOKEN")
        self.channel = os.environ.get("SLACK_CHANNEL", "#security-alerts")
        self.enabled = os.environ.get("SLACK_NOTIFICATIONS_ENABLED", "false").lower() == "true"
        
        # Critical resources/actions that trigger notifications
        self.critical_resources = set(
            os.environ.get("SLACK_CRITICAL_RESOURCES", "").split(",")
        )
        self.critical_actions = set(
            os.environ.get("SLACK_CRITICAL_ACTIONS", "").split(",")
        )
        
        # Initialize Slack client if bot token is available
        self.client = None
        if self.bot_token:
            self.client = WebClient(token=self.bot_token)

    def is_critical_denial(
        self,
        resource: str,
        action: str,
        decision: bool
    ) -> bool:
        """
        Check if a denial is critical and should trigger a notification.
        
        A denial is critical if:
        1. The decision is denied (False)
        2. The resource or action is in the critical lists
        """
        if decision:  # Not a denial
            return False
        
        # Check if resource is critical
        if resource in self.critical_resources:
            return True
        
        # Check if action is critical
        if action in self.critical_actions:
            return True
        
        return False

    def send_denial_notification(
        self,
        agent_id: int,
        resource: str,
        action: str,
        reason: Optional[str] = None,
        timestamp: Optional[datetime] = None
    ) -> bool:
        """
        Send a Slack notification for a critical denial.
        
        Returns True if notification was sent successfully.
        """
        if not self.enabled:
            logger.debug("Slack notifications are disabled")
            return False
        
        if not self.webhook_url and not self.client:
            logger.warning("Slack webhook URL or bot token not configured")
            return False
        
        # Format timestamp
        if timestamp is None:
            timestamp = datetime.utcnow()
        
        timestamp_str = timestamp.strftime("%Y-%m-%d %H:%M:%S UTC")
        
        # Create message blocks
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "🚨 Critical Access Denied",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Agent ID:*\n{agent_id}"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Resource:*\n{resource}"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Action:*\n{action}"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Timestamp:*\n{timestamp_str}"
                    }
                ]
            }
        ]
        
        # Add reason if provided
        if reason:
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Reason:*\n{reason}"
                }
            })
        
        # Add context
        blocks.append({
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "This alert was generated by AgentIAM security monitoring"
                }
            ]
        })
        
        # Send notification
        try:
            if self.client:
                # Use Slack API
                response = self.client.chat_postMessage(
                    channel=self.channel,
                    text=f"Critical Access Denied: Agent {agent_id} denied {action} on {resource}",
                    blocks=blocks
                )
                return response["ok"]
            else:
                # Use webhook
                import requests
                payload = {
                    "text": f"Critical Access Denied: Agent {agent_id} denied {action} on {resource}",
                    "blocks": blocks
                }
                response = requests.post(
                    self.webhook_url,
                    json=payload,
                    timeout=10
                )
                return response.status_code == 200
        except SlackApiError as e:
            logger.error(f"Slack API error: {e}")
            return False
        except Exception as e:
            logger.error(f"Error sending Slack notification: {e}")
            return False


# Singleton instance
slack_service = SlackService()
